# src/main/resources/application.yml
frontend:
  url: http://localhost:3000/

backend:
  url: http://localhost:8080/

website:
  domain: localhost



spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/computeralerts
      database: computeralerts

server:
  port: 8080 # Default port for Spring Boot




auth0:
    clientId: PWoMxp7p4Gt69pA3kfnJdXXyINtua5qB
    clientSecret: wsBITK-BPpOf-DLOvMjjNU1wicWFHfUol-3hbZ0M2r6BwY9RUClcu0lj9ZGTsEuN
    domain: dev-im24qkb6l7t2yhha.ca.auth0.com
